#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BUILD_DIR="${BSRVCORE_BUILD_DIR:-build-release}"
BUILD_TYPE="${BSRVCORE_BUILD_TYPE:-Release}"
BUILD_TESTS="${BSRVCORE_BUILD_TESTS:-ON}"
BUILD_EXAMPLES="${BSRVCORE_BUILD_EXAMPLES:-ON}"
BUILD_BENCHMARKS="${BSRVCORE_BUILD_BENCHMARKS:-ON}"
BUILD_TOOLS="${BSRVCORE_BUILD_TOOLS:-ON}"
BUNDLED_WRK="${BSRVCORE_BENCHMARK_BUILD_BUNDLED_WRK:-OFF}"
PARALLELISM="${BSRVCORE_BUILD_PARALLEL:-$(nproc)}"

cmake -S "${ROOT_DIR}" -B "${ROOT_DIR}/${BUILD_DIR}" \
  -DCMAKE_BUILD_TYPE="${BUILD_TYPE}" \
  -DBSRVCORE_BUILD_TESTS="${BUILD_TESTS}" \
  -DBSRVCORE_BUILD_EXAMPLES="${BUILD_EXAMPLES}" \
  -DBSRVCORE_BUILD_BENCHMARKS="${BUILD_BENCHMARKS}" \
  -DBSRVCORE_BUILD_TOOLS="${BUILD_TOOLS}" \
  -DBSRVCORE_BENCHMARK_BUILD_BUNDLED_WRK="${BUNDLED_WRK}"

if [[ "$#" -gt 0 ]]; then
  cmake --build "${ROOT_DIR}/${BUILD_DIR}" --parallel "${PARALLELISM}" \
    --target "$@"
else
  cmake --build "${ROOT_DIR}/${BUILD_DIR}" --parallel "${PARALLELISM}"
fi
