name: CI & Package

# Triggered by any push (branch or tag). In the job, we decide whether to upload a release based on whether it's a tag.
on:
  push: {}

jobs:
  build-and-package:
    name: Build, Package (DEB/RPM/TGZ)
    runs-on: ubuntu-latest

    # Grant 'contents: write' permission to the GITHUB_TOKEN for this job (required to create release).
    permissions:
      contents: write

    steps:
      # 1) Checkout source code (fetch tags as well to ensure tag detection)
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 2) Install a suitable version of CMake (your CMakeLists requires >= 3.25)
      - name: Install CMake >= 3.25
        uses: lukka/get-cmake@latest
        with:
          cmake-version: '3.25.0'

      # 3) Install system dependencies
      - name: Install apt packages (build + packagers + openssl dev)
        run: |
          sudo apt-get update
          packages=(
            build-essential     # Core toolchain
            ninja-build         # Ninja generator (if you use -G Ninja later)
            pkg-config          # For pkg-config checks
            libboost-all-dev    # Boost (dev headers/libs)
            dpkg-dev            # dpkg helpers (dpkg-shlibdeps etc.)
            fakeroot            # For building .deb without real root
            rpm                 # For generating RPMs with CPack
            ca-certificates     # network certs (safe)
            libssl-dev          # OpenSSL (headers + libcrypto) — project depends on openssl/crypto
          )
          sudo apt-get install -y --no-install-recommends "${packages[@]}"

      # 4) Configure (out-of-source build)
      - name: Configure with CMake
        run: |
          # Enable testing so CTest can discover tests (requires your CMakeLists to call enable_testing/add_test)
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr -DBSRVCORE_BUILD_TESTING=ON

      # 5) Build
      - name: Build
        run: cmake --build build --parallel

      # 5.1) Run tests with CTest (fail the job if tests fail)
      - name: Run tests with CTest
        run: |
          cd build
          # run tests with output on failure and parallelism
          ctest --output-on-failure --parallel $(nproc)

      # 6) Package: Run CPack to generate DEB/RPM/TGZ (try multiple generators)
      - name: Package with CPack (DEB, RPM, TGZ)
        run: |
          cd build
          # try each generator; failures won't stop the job (they'll be echoed)
          cpack -G DEB || echo "DEB generation failed or produced no packages"
          cpack -G RPM || echo "RPM generation failed or produced no packages"
          cpack -G TGZ || echo "TGZ generation failed or produced no packages"

      # 6.1) Collect all produced packages into a single folder for upload
      - name: Collect generated packages
        run: |
          mkdir -p packages
          # recursively find typical package file extensions produced by CPack
          find . -type f \( -name "*.deb" -o -name "*.rpm" -o -name "*.tar.gz" -o -name "*.tgz" \) -print0 \
            | xargs -0 -I{} bash -lc 'cp -v "{}" packages/ || true'
          echo "Collected files:"
          ls -lah packages || true

      # 7) Upload the built packages as workflow artifacts (for debugging)
      - name: Upload packages as workflow artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/*

      # 8) Create GitHub Release and upload packages if this is a tag starting with 'v'
      - name: Create GitHub Release and upload packages (tags like v1.2.3)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            packages/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

