name: CI & Package

# Triggered by any push (branch or tag). In the job, we decide whether to upload a release based on whether it's a tag.
on:
  push: {}

jobs:
  build-and-package:
    name: Build, Package (DEB/RPM/TGZ)
    runs-on: ubuntu-latest

    # --- FIX STARTS HERE ---
    # Grant 'contents: write' permission to the GITHUB_TOKEN for this job.
    # This is required by the action-gh-release step to create a release.
    permissions:
      contents: write
    # --- FIX ENDS HERE ---

    steps:
      # 1) Checkout source code
      - name: Checkout source
        uses: actions/checkout@v4

      # 2) Install a suitable version of CMake (your CMakeLists requires >= 3.25)
      - name: Install CMake >= 3.25
        uses: lukka/get-cmake@latest
        with:
          cmake-version: '3.25.0'

      # 3) Install system dependencies
      - name: Install apt packages (build + packagers)
        run: |
          sudo apt-get update
          packages=(
            build-essential     # Core toolchain
            ninja-build         # Ninja generator (if you use -G Ninja later)
            pkg-config          # For pkg-config checks
            libboost-all-dev    # Boost (dev headers/libs)
            dpkg-dev            # Needed for deb helper tools (dpkg-shlibdeps, etc.)
            fakeroot            # For building .deb without real root
            rpm                 # For generating RPMs with CPack
          )
          sudo apt-get install -y --no-install-recommends "${packages[@]}"

      # 4) Configure (out-of-source build)
      - name: Configure with CMake
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr

      # 5) Build
      - name: Build
        run: cmake --build build --parallel

      # 6) Package: Run CPack to generate DEB/RPM/TGZ
      - name: Package with CPack (DEB, RPM, TGZ)
        run: |
          cd build
          cpack -G DEB || echo "DEB generation failed or skipped"
          cpack -G RPM || echo "RPM generation failed or skipped"
          cpack -G TGZ || echo "TGZ generation failed or skipped"

      # 7) Upload the built packages as workflow artifacts
      - name: Upload packages as workflow artifact (for debugging)
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz

      # 8) If this is a tag starting with 'v', create a GitHub Release
      - name: Create GitHub Release and upload packages (tags like v1.2.3)
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v2 # Suggest using a more recent version like v2
        with:
          files: |
            build/*.deb
            build/*.rpm
            build/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

